// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_invitees_id_ from "./routes/api/invitees/[id].ts";
import * as $api_invitees_csv from "./routes/api/invitees/csv.ts";
import * as $api_invitees_index from "./routes/api/invitees/index.ts";
import * as $api_notify_index from "./routes/api/notify/index.ts";
import * as $api_purge from "./routes/api/purge.ts";
import * as $api_settings_index from "./routes/api/settings/index.ts";
import * as $api_users_index from "./routes/api/users/index.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.ts";
import * as $logout from "./routes/logout.ts";
import * as $Badge from "./islands/Badge.tsx";
import * as $InviteeList from "./islands/InviteeList.tsx";
import * as $LazyImage from "./islands/LazyImage.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $Logo from "./islands/Logo.tsx";
import * as $Modal from "./islands/Modal.tsx";
import * as $MultiPersonInput from "./islands/MultiPersonInput.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/invitees/[id].ts": $api_invitees_id_,
    "./routes/api/invitees/csv.ts": $api_invitees_csv,
    "./routes/api/invitees/index.ts": $api_invitees_index,
    "./routes/api/notify/index.ts": $api_notify_index,
    "./routes/api/purge.ts": $api_purge,
    "./routes/api/settings/index.ts": $api_settings_index,
    "./routes/api/users/index.ts": $api_users_index,
    "./routes/index.tsx": $index,
    "./routes/login.ts": $login,
    "./routes/logout.ts": $logout,
  },
  islands: {
    "./islands/Badge.tsx": $Badge,
    "./islands/InviteeList.tsx": $InviteeList,
    "./islands/LazyImage.tsx": $LazyImage,
    "./islands/Login.tsx": $Login,
    "./islands/Logo.tsx": $Logo,
    "./islands/Modal.tsx": $Modal,
    "./islands/MultiPersonInput.tsx": $MultiPersonInput,
    "./islands/RegisterForm.tsx": $RegisterForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
