import Login from "../../islands/Login.tsx";

interface FooterProps {
  admin: boolean;
}

export default function Footer({ admin }: FooterProps) {
  return (
    <footer class="footer">
      <Login loggedIn={admin}/>
      <p>
        <span>Made with <i class="icon-heart"></i> by Phil</span>
        <span>Built with <a href="https://fresh.deno.dev/" target="_blank">fresh by deno</a> </span>
        <span>Example images generated by AI</span>
      </p>
    </footer>
  );
}
