export const {
  SESSION_KEY,
  SESSION_LIFETIME,
  ADMIN_USER,
  ADMIN_PASSWORD,
  LOGIN_ATTEMPTS_COUNT,
  LOGIN_ATTEMPTS_TIMEOUT,
  SMTP_SERVER,
  SMTP_USER,
  SMTP_PASSWORD,
  MAILERSEND_EMAIL,
  MAILERSEND_API_TOKEN,
  EMAIL_ENABLED
} = Deno.env.toObject();
